version: '3'
services:
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - '6380:6379'
  #   volumes:
  #     - .data/redis:/data
  #   environment:
  #     REDIS_PASSWORD: redis
  user-wallet:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wallet
    ports:
      - '5433:5432'
